"use client";
import Head from "next/head";
import { Footer, Home, ModalContent } from "@/library";
import { Dialog } from "@mui/material";
import { useCallback, useState } from "react";

type Values = {
  email: string;
};

export default function Page() {
  const [open, setOpen] = useState(false);
  const [values, setValues] = useState<Values>({ email: "" });

  const onClose = useCallback(() => {
    setOpen(false);
  }, []);

  const onSubmit = useCallback((values: Values) => {
    setValues(values);
    setOpen(true);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home
        waitingForm={{
          defaultValues: values,
          onSubmit,
        }}
      />
      <Footer />
      <Dialog open={open} onClose={onClose}>
        <ModalContent email={{ email: values.email }} />
      </Dialog>
    </>
  );
}
